create table `admin_accounts` (`id` text not null primary key, `email` text not null, `email_normalized` text not null, `password_hash` text not null, `role` text not null, `status` text not null default 'active', `created_at` datetime not null, `updated_at` datetime not null);
create unique index `uq_admin_accounts_email_normalized` on `admin_accounts` (`email_normalized`);
create table `admin_webauthn_credentials` (`id` text not null primary key, `admin_account_id` text not null, `credential_id` text not null, `public_key` text not null, `sign_count` integer not null default 0, `transports` text null, `aaguid` text null, `nickname` text null, `last_used_at` datetime null, `created_at` datetime not null);
create unique index `uq_admin_webauthn_credential_id` on `admin_webauthn_credentials` (`credential_id`);
create index `idx_admin_webauthn_admin` on `admin_webauthn_credentials` (`admin_account_id`);
create table `announcements` (`id` text not null primary key, `title` text not null, `body_markdown` text not null, `status` text not null default 'draft', `importance` text not null default 'normal', `publish_start_at` datetime null, `publish_end_at` datetime null, `created_by` text not null, `created_at` datetime not null, `updated_at` datetime not null);
create table `api_keys` (`id` text not null primary key, `user_id` text not null, `key_hash` text not null, `label` text null, `scope` text not null, `status` text not null default 'active', `last_used_at` datetime null, `created_at` datetime not null, `revoked_at` datetime null);
create unique index `uq_api_keys_key_hash` on `api_keys` (`key_hash`);
create index `idx_api_keys_user_status` on `api_keys` (`user_id`, `status`);
create table `app_settings` (`key` text not null primary key, `value` text not null, `updated_at` datetime not null);
create table `audit_logs` (`id` text not null primary key, `event_type` text not null, `actor_type` text not null, `actor_id` text null, `target_type` text null, `target_id` text null, `result` text not null, `metadata` text null, `occurred_at` datetime not null);
create index `idx_audit_logs_occurred` on `audit_logs` (`occurred_at`);
create index `idx_audit_logs_actor` on `audit_logs` (`actor_type`, `actor_id`);
create index `idx_audit_logs_target` on `audit_logs` (`target_type`, `target_id`);
create trigger `trg_audit_logs_no_update` before update on `audit_logs` begin select raise(abort, 'audit_logs is append-only'); end;
create trigger `trg_audit_logs_no_delete` before delete on `audit_logs` begin select raise(abort, 'audit_logs is append-only'); end;
create table `email_notifications` (`id` text not null primary key, `subject` text not null, `template_key` text not null, `target_condition` text not null, `status` text not null default 'draft', `created_by` text not null, `sent_at` datetime null, `created_at` datetime not null);
create table `help_articles` (`id` text not null primary key, `title` text not null, `slug` text not null, `category` text null, `body_markdown` text not null, `status` text not null default 'unpublished', `updated_by` text not null, `created_at` datetime not null, `updated_at` datetime not null);
create unique index `uq_help_articles_slug` on `help_articles` (`slug`);
create table `inquiries` (`id` text not null primary key, `category` text not null, `subject` text null, `body` text not null, `contact_email` text null, `status` text not null default 'OPEN', `created_by_user_id` text null, `created_at` datetime not null, `updated_at` datetime not null);
create table `policies` (`id` text not null primary key, `type` text not null, `version` integer not null, `body_markdown` text not null, `is_published` integer not null default false, `requires_reconsent` integer not null default false, `effective_date` datetime not null, `edited_by` text not null, `created_at` datetime not null);
create unique index `uq_policies_type_version` on `policies` (`type`, `version`);
create table `reports` (`id` text not null primary key, `target_user_id` text null, `target_handle` text not null, `reason_category` text not null, `detail` text null, `contact_email` text null, `status` text not null default 'OPEN', `duplicate_count` integer not null default 1, `inquiry_id` text null, `created_at` datetime not null, `updated_at` datetime not null);
create index `idx_reports_target_status` on `reports` (`target_user_id`, `status`);
create table `suspensions` (`id` text not null primary key, `user_id` text not null, `reason_category` text not null, `status` text not null default 'active', `suspended_by` text not null, `suspended_at` datetime not null, `lifted_at` datetime null);
create index `idx_suspensions_user_status` on `suspensions` (`user_id`, `status`);
create table `unfreeze_requests` (`id` text not null primary key, `user_id` text not null, `suspension_id` text null, `reason` text not null, `supplement` text null, `status` text not null default 'PENDING', `reviewed_by` text null, `created_at` datetime not null, `reviewed_at` datetime null);
create index `idx_unfreeze_user_created` on `unfreeze_requests` (`user_id`, `created_at`);
create table `users` (`id` text not null primary key, `email` text not null, `email_normalized` text not null, `password_hash` text not null, `status` text not null, `email_verified_at` datetime null, `session_epoch` integer not null default 0, `announcement_email_opt_in` integer not null default true, `created_at` datetime not null, `updated_at` datetime not null);
create unique index `uq_users_email_normalized` on `users` (`email_normalized`);
create table `profiles` (`id` text not null primary key, `user_id` text not null, `handle` text not null, `visibility` text not null default 'public', `icon_image_id` text null, `first_name` text not null default '', `last_name` text not null default '', `name_display_order` text not null default 'givenNameFirst', `occupation` text null, `search_name` text null, `bio` text null, `created_at` datetime not null, `updated_at` datetime not null, constraint `profiles_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on update cascade on delete cascade);
create unique index `uq_profiles_user_id` on `profiles` (`user_id`);
create unique index `uq_profiles_handle` on `profiles` (`handle`);
create index `idx_profiles_visibility_updated` on `profiles` (`visibility`, `updated_at`);
create index `idx_profiles_occupation` on `profiles` (`occupation`);
create index `idx_profiles_search_name` on `profiles` (`search_name`);
create table `sns_links` (`id` text not null primary key, `profile_id` text not null, `platform` text not null, `url` text not null, `label` text null, `sort_order` integer not null default 0, `created_at` datetime not null, constraint `sns_links_profile_id_foreign` foreign key (`profile_id`) references `profiles` (`id`) on update cascade on delete cascade);
create index `sns_links_profile_id_index` on `sns_links` (`profile_id`);
create index `idx_sns_links_profile_sort` on `sns_links` (`profile_id`, `sort_order`);
